[2024-04-11T17:05:02.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:05:02.815+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2_v02.load_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:05:02.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2_v02.load_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:05:02.820+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T17:05:02.825+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-04-10 17:00:00+00:00
[2024-04-11T17:05:02.834+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3352) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:05:02.835+0000] {standard_task_runner.py:63} INFO - Started process 3354 to run task
[2024-04-11T17:05:02.836+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2_v02', 'load_data', 'scheduled__2024-04-10T17:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpujz728ti']
[2024-04-11T17:05:02.837+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask load_data
[2024-04-11T17:05:02.880+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2_v02.load_data scheduled__2024-04-10T17:00:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T17:05:02.934+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2_v02' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-10T17:00:00+00:00'
[2024-04-11T17:05:02.935+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:05:02.948+0000] {postgres.py:175} INFO - Running copy expert: COPY online_retail FROM STDIN, filename: <_io.TextIOWrapper name='/opt/airflow/include/dataset/processed_online_retail.csv' mode='r' encoding='UTF-8'>
[2024-04-11T17:05:02.948+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:05:02.948+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exercise.py", line 46, in load_data
    pg_hook.bulk_load('online_retail', f)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 197, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in copy_expert
    if not os.path.isfile(filename):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not TextIOWrapper
[2024-04-11T17:05:02.956+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=22655381_DAG2_v02, task_id=load_data, execution_date=20240410T170000, start_date=20240411T170502, end_date=20240411T170502
[2024-04-11T17:05:02.961+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task load_data (stat: path should be string, bytes, os.PathLike or integer, not TextIOWrapper; 3354)
[2024-04-11T17:05:02.989+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-11T17:05:03.001+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:05:03.002+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
