[2024-04-11T17:17:13.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:17:13.868+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:17:13.886+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [queued]>
[2024-04-11T17:17:13.886+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T17:17:13.897+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data> on 2024-04-10 17:00:00+00:00
[2024-04-11T17:17:13.908+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4374) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:17:13.909+0000] {standard_task_runner.py:63} INFO - Started process 4376 to run task
[2024-04-11T17:17:13.912+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2', 'insert_data', 'scheduled__2024-04-10T17:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmpzscsuosv']
[2024-04-11T17:17:13.914+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask insert_data
[2024-04-11T17:17:13.955+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2.insert_data scheduled__2024-04-10T17:00:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T17:17:14.007+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-10T17:00:00+00:00'
[2024-04-11T17:17:14.007+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:17:14.021+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-11T17:17:14.884+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:17:14.888+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_exercise.py", line 47, in load_data
    cursor.copy_expert("COPY online_retail FROM STDIN WITH CSV HEADER", f)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(10)
CONTEXT:  COPY online_retail, line 4408, column stockcode: "BANK CHARGES"

[2024-04-11T17:17:14.936+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=22655381_DAG2, task_id=insert_data, execution_date=20240410T170000, start_date=20240411T171713, end_date=20240411T171714
[2024-04-11T17:17:15.077+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 111 for task insert_data (value too long for type character varying(10)
CONTEXT:  COPY online_retail, line 4408, column stockcode: "BANK CHARGES"
; 4376)
[2024-04-11T17:17:15.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-11T17:17:15.248+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:17:15.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
