[2024-04-11T17:50:52.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T17:50:52.318+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v3.second_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-04-11T17:50:52.339+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v3.second_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-04-11T17:50:52.340+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-11T17:50:52.363+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-01-01 00:00:00+00:00
[2024-04-11T17:50:52.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v3', 'second_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp48ytsn96']
[2024-04-11T17:50:52.378+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask second_task
[2024-04-11T17:50:52.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T17:50:52.381+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2024-04-11T17:50:52.505+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_v3.second_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host caed5d205145
[2024-04-11T17:50:52.645+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-04-11T17:50:52.649+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T17:50:52.666+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-11T17:50:52.667+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "This seems like my task 1 is working fine"']
[2024-04-11T17:50:52.679+0000] {subprocess.py:86} INFO - Output:
[2024-04-11T17:50:52.681+0000] {subprocess.py:93} INFO - This seems like my task 1 is working fine
[2024-04-11T17:50:52.683+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-11T17:50:52.700+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T17:50:52.782+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=first_dag_v3, task_id=second_task, execution_date=20240101T000000, start_date=20240411T175052, end_date=20240411T175052
[2024-04-11T17:50:52.889+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T17:50:52.945+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T17:50:52.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
