[2024-04-11T15:14:20.194+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T15:14:20.210+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v05.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:14:20.218+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v05.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:14:20.219+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T15:14:20.235+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bigquery> on 2024-04-09 17:00:00+00:00
[2024-04-11T15:14:20.312+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T15:14:20.294+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_gg_bigquery_v05', 'load_csv_to_bigquery', 'scheduled__2024-04-09T17:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_gg_bigquery.py', '--cfg-path', '/tmp/tmpsj0jk795']
[2024-04-11T15:14:20.314+0000] {standard_task_runner.py:63} INFO - Started process 5211 to run task
[2024-04-11T15:14:20.315+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask load_csv_to_bigquery
[2024-04-11T15:14:20.480+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_gg_bigquery_v05.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [running]> on host a4f2bd86ee13
[2024-04-11T15:14:20.613+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='dag_with_gg_bigquery_v05' AIRFLOW_CTX_TASK_ID='load_csv_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T17:00:00+00:00'
[2024-04-11T15:14:20.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T15:14:20.672+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-11T15:14:20.675+0000] {base.py:84} INFO - Using connection ID 'gcp' for task execution.
[2024-04-11T15:14:20.678+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-04-11T15:14:20.758+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: retail.online_retail; using project "***-projecct"
[2024-04-11T15:14:20.759+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': '***-projecct', 'datasetId': 'retail', 'tableId': 'online_retail'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://***_online_retail_lab7/raw/online_retail.csv'], 'writeDisposition': 'WRITE_EMPTY', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-04-11T15:14:20.765+0000] {bigquery.py:1613} INFO - Inserting job ***_dag_with_gg_bigquery_v05_load_csv_to_bigquery_2024_04_09T17_00_00_00_00_cb5ae31c0fa5b3ccf2e800970164d093
[2024-04-11T15:14:22.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T15:14:22.745+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Conflict: 409 Already Exists: Table airflow-projecct:retail.online_retail; reason: duplicate, message: Already Exists: Table airflow-projecct:retail.online_retail
[2024-04-11T15:14:22.755+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_gg_bigquery_v05, task_id=load_csv_to_bigquery, execution_date=20240409T170000, start_date=20240411T151420, end_date=20240411T151422
[2024-04-11T15:14:22.763+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task load_csv_to_bigquery (409 Already Exists: Table airflow-projecct:retail.online_retail; reason: duplicate, message: Already Exists: Table airflow-projecct:retail.online_retail; 5211)
[2024-04-11T15:14:22.780+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-11T15:14:22.816+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T15:14:22.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
