[2024-04-11T15:38:52.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T15:38:52.352+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v06.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:38:52.358+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_gg_bigquery_v06.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [queued]>
[2024-04-11T15:38:52.359+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 5
[2024-04-11T15:38:52.365+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bigquery> on 2024-04-09 17:00:00+00:00
[2024-04-11T15:38:52.376+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6848) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T15:38:52.377+0000] {standard_task_runner.py:63} INFO - Started process 6850 to run task
[2024-04-11T15:38:52.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_gg_bigquery_v06', 'load_csv_to_bigquery', 'scheduled__2024-04-09T17:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_gg_bigquery.py', '--cfg-path', '/tmp/tmpq0jq9blt']
[2024-04-11T15:38:52.379+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask load_csv_to_bigquery
[2024-04-11T15:38:52.415+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_gg_bigquery_v06.load_csv_to_bigquery scheduled__2024-04-09T17:00:00+00:00 [running]> on host a4f2bd86ee13
[2024-04-11T15:38:52.485+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='duy' AIRFLOW_CTX_DAG_ID='dag_with_gg_bigquery_v06' AIRFLOW_CTX_TASK_ID='load_csv_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T17:00:00+00:00'
[2024-04-11T15:38:52.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T15:38:52.508+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-11T15:38:52.508+0000] {base.py:84} INFO - Using connection ID 'gcp' for task execution.
[2024-04-11T15:38:52.509+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-04-11T15:38:52.556+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: retail.online_retail; using project "***-projecct"
[2024-04-11T15:38:52.557+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': '***-projecct', 'datasetId': 'retail', 'tableId': 'online_retail'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://***_online_retail_lab7/raw/online_retail.csv'], 'writeDisposition': 'WRITE_EMPTY', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-04-11T15:38:52.558+0000] {bigquery.py:1613} INFO - Inserting job ***_dag_with_gg_bigquery_v06_load_csv_to_bigquery_2024_04_09T17_00_00_00_00_3e519b010c40bf6564dfb141c3700baa
[2024-04-11T15:38:54.448+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T15:38:54.451+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Conflict: 409 Already Exists: Table airflow-projecct:retail.online_retail; reason: duplicate, message: Already Exists: Table airflow-projecct:retail.online_retail
[2024-04-11T15:38:54.464+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_gg_bigquery_v06, task_id=load_csv_to_bigquery, execution_date=20240409T170000, start_date=20240411T153852, end_date=20240411T153854
[2024-04-11T15:38:54.479+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task load_csv_to_bigquery (409 Already Exists: Table airflow-projecct:retail.online_retail; reason: duplicate, message: Already Exists: Table airflow-projecct:retail.online_retail; 6850)
[2024-04-11T15:38:54.531+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-11T15:38:54.560+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class BigQueryExecuteQueryOperator. (This operator is deprecated. Please use `BigQueryInsertJobOperator`.)
[2024-04-11T15:38:54.582+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T15:38:54.584+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
