[2024-04-11T16:51:29.822+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T16:51:29.853+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22655381_DAG2_v01.create_table scheduled__2024-04-11T16:50:00+00:00 [queued]>
[2024-04-11T16:51:29.861+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22655381_DAG2_v01.create_table scheduled__2024-04-11T16:50:00+00:00 [queued]>
[2024-04-11T16:51:29.861+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-11T16:51:29.870+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_table> on 2024-04-11 16:50:00+00:00
[2024-04-11T16:51:29.884+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2159) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-11T16:51:29.896+0000] {standard_task_runner.py:63} INFO - Started process 2161 to run task
[2024-04-11T16:51:29.892+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '22655381_DAG2_v01', 'create_table', 'scheduled__2024-04-11T16:50:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_exercise.py', '--cfg-path', '/tmp/tmp5zlevx0r']
[2024-04-11T16:51:29.901+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask create_table
[2024-04-11T16:51:29.983+0000] {task_command.py:426} INFO - Running <TaskInstance: 22655381_DAG2_v01.create_table scheduled__2024-04-11T16:50:00+00:00 [running]> on host 51938eebcb2b
[2024-04-11T16:51:30.037+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Van Duy' AIRFLOW_CTX_DAG_ID='22655381_DAG2_v01' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T16:50:00+00:00'
[2024-04-11T16:51:30.038+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T16:51:30.038+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS online_retail (
            InvoiceNo VARCHAR(10),
            StockCode VARCHAR(10),
            Description TEXT,
            Quantity INT,
            InvoiceDate TIMESTAMP,
            UnitPrice FLOAT,
            CustomerID INT,
            Country VARCHAR(50)
        )
[2024-04-11T16:51:30.048+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T16:51:30.056+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn_id` isn't defined
[2024-04-11T16:51:30.063+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=22655381_DAG2_v01, task_id=create_table, execution_date=20240411T165000, start_date=20240411T165129, end_date=20240411T165130
[2024-04-11T16:51:30.070+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task create_table (The conn_id `postgres_conn_id` isn't defined; 2161)
[2024-04-11T16:51:30.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-11T16:51:30.091+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-11T16:51:30.117+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-11T16:51:30.119+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
